// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFC0Ibtct0tqtAuIvBldKJelJewawfuxk',
    appId: '1:53894953833:web:7b007d098bca14b2259bf8',
    messagingSenderId: '53894953833',
    projectId: 'cinemabookingv4',
    authDomain: 'cinemabookingv4.firebaseapp.com',
    storageBucket: 'cinemabookingv4.appspot.com',
    measurementId: 'G-FC2MNVQ2TH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzKGTNnn4wriYBegGet82ruVTWOlk5U5E',
    appId: '1:53894953833:android:3f802267a6388574259bf8',
    messagingSenderId: '53894953833',
    projectId: 'cinemabookingv4',
    storageBucket: 'cinemabookingv4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDih3XNk6b7gKY9Mbrk6EKAKgcLS9OjEqE',
    appId: '1:53894953833:ios:af3fc240d01fac43259bf8',
    messagingSenderId: '53894953833',
    projectId: 'cinemabookingv4',
    storageBucket: 'cinemabookingv4.appspot.com',
    iosBundleId: 'com.example.cinemaBookingV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDih3XNk6b7gKY9Mbrk6EKAKgcLS9OjEqE',
    appId: '1:53894953833:ios:dac4393457b5608a259bf8',
    messagingSenderId: '53894953833',
    projectId: 'cinemabookingv4',
    storageBucket: 'cinemabookingv4.appspot.com',
    iosBundleId: 'com.example.cinemaBookingV2.RunnerTests',
  );
}
